In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [3]:
df = pd.read_csv('survey lung cancer.csv')

In [4]:
X_df = pd.get_dummies(df, drop_first=True,dtype=int)

In [5]:
X_df

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M,LUNG_CANCER_YES
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1,1
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1,1
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0,0
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1,0
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,1,1,2,2,2,1,1,2,2,2,2,1,0,1
305,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1,1
306,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1,1
307,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1,1
308,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1,1

In [6]:
y = X_df["LUNG_CANCER_YES"]

In [7]:
X_df

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M,LUNG_CANCER_YES
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1,1
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1,1
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0,0
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1,0
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,1,1,2,2,2,1,1,2,2,2,2,1,0,1
305,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1,1
306,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1,1
307,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1,1
308,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1,1

In [8]:
indep=X_df[['ALLERGY ', 'WHEEZING', 'ALCOHOL CONSUMING', 'COUGHING', 'SWALLOWING DIFFICULTY']]
dep=X_df['LUNG_CANCER_YES']

In [9]:
indep

     ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  SWALLOWING DIFFICULTY
0           1         2                  2         2                      2
1           2         1                  1         1                      2
2           1         2                  1         2                      1
3           1         1                  2         1                      2
4           1         2                  1         2                      1
..        ...       ...                ...       ...                    ...
304         1         1                  2         2                      2
305         2         2                  2         2                      1
306         2         2                  2         2                      1
307         2         1                  2         2                      1
308         2         2                  2         1                      2

[309 rows x 5 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 42)

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(random_state = 0)
model.fit(X_train, y_train)

C:\anaconda\envs\aiml\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=0, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [22]:
y_pred= model.predict(X_test)
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Logistic Regression Accuracy: 0.9514563106796117
              precision    recall  f1-score   support

           0       0.67      0.57      0.62         7
           1       0.97      0.98      0.97        96

    accuracy                           0.95       103
   macro avg       0.82      0.78      0.79       103
weighted avg       0.95      0.95      0.95       103

In [23]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred )

In [24]:
print(cm)

[[ 4  3]
 [ 2 94]]

In [25]:
import pickle

In [26]:
filename="Lung_cancer_5feature_model.sav"

In [27]:
pickle.dump(model,open(filename,'wb'))
loaded_model=pickle.load(open(filename,'rb'))

In [ ]:
import numpy as np

data_alg = int(input("ALLERGY (1 or 2): "))
data_wz = int(input("WHEEZING (1 or 2): "))
data_ac = int(input("ALCOHOL CONSUMING (1 or 2): "))
data_cog = int(input("COUGHING (1 or 2): "))
data_sd = int(input("SWALLOWING DIFFICULTY (1 or 2): "))

In [38]:
prediction = loaded_model.predict([[data_alg, data_wz, data_ac, data_cog, data_sd]])
prediction

array([1])

In [39]:
print(f"Prediction: {prediction}")
if prediction[0] == 1:
    print("Lung Cancer Prediction Result: Positive")
else:
    print("Lung Cancer Prediction Result: Negative")

Prediction: [1]
Lung Cancer Prediction Result: Positive