In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df = pd.read_csv('survey lung cancer.csv')

In [3]:
X_df = pd.get_dummies(df, drop_first=True,dtype=int)

In [4]:
X_df

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M,LUNG_CANCER_YES
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1,1
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1,1
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0,0
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1,0
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,1,1,2,2,2,1,1,2,2,2,2,1,0,1
305,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1,1
306,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1,1
307,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1,1
308,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1,1

In [5]:
y = X_df["LUNG_CANCER_YES"]

In [6]:
X_df

,AGE,SMOKING,YELLOW_FINGERS,ANXIETY,PEER_PRESSURE,CHRONIC DISEASE,FATIGUE,ALLERGY,WHEEZING,ALCOHOL CONSUMING,COUGHING,SHORTNESS OF BREATH,SWALLOWING DIFFICULTY,CHEST PAIN,GENDER_M,LUNG_CANCER_YES
0,69,1,2,2,1,1,2,1,2,2,2,2,2,2,1,1
1,74,2,1,1,1,2,2,2,1,1,1,2,2,2,1,1
2,59,1,1,1,2,1,2,1,2,1,2,2,1,2,0,0
3,63,2,2,2,1,1,1,1,1,2,1,1,2,2,1,0
4,63,1,2,1,1,1,1,1,2,1,2,2,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
304,56,1,1,1,2,2,2,1,1,2,2,2,2,1,0,1
305,70,2,1,1,1,1,2,2,2,2,2,2,1,2,1,1
306,58,2,1,1,1,1,1,2,2,2,2,1,1,2,1,1
307,67,2,1,2,1,1,2,2,1,2,2,2,1,2,1,1
308,62,1,1,1,2,1,2,2,2,2,1,1,2,1,1,1

In [7]:
indep=X_df[['ALLERGY ', 'WHEEZING', 'ALCOHOL CONSUMING', 'COUGHING', 'SWALLOWING DIFFICULTY']]
dep=X_df['LUNG_CANCER_YES']

In [8]:
indep

     ALLERGY   WHEEZING  ALCOHOL CONSUMING  COUGHING  SWALLOWING DIFFICULTY
0           1         2                  2         2                      2
1           2         1                  1         1                      2
2           1         2                  1         2                      1
3           1         1                  2         1                      2
4           1         2                  1         2                      1
..        ...       ...                ...       ...                    ...
304         1         1                  2         2                      2
305         2         2                  2         2                      1
306         2         2                  2         2                      1
307         2         1                  2         2                      1
308         2         2                  2         1                      2

[309 rows x 5 columns]

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_scaled, y)

LogisticRegression()

In [16]:
Y_pred=model.predict(X_test)

In [19]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,Y_pred )

In [20]:
print(cm)

[[ 7  9]
 [ 4 83]]

In [22]:
from sklearn.metrics import classification_report
clf_report=classification_report(y_test,Y_pred )

In [23]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.64      0.44      0.52        16
           1       0.90      0.95      0.93        87

    accuracy                           0.87       103
   macro avg       0.77      0.70      0.72       103
weighted avg       0.86      0.87      0.86       103

In [25]:
import pickle

In [26]:
pickle.dump(model, open("Lung_cancer_5feature_model.sav", 'wb'))
pickle.dump(sc, open("scaler_5feature.pkl", 'wb'))

In [27]:
loaded_model = pickle.load(open("Lung_cancer_5feature_model.sav", 'rb'))
loaded_scaler = pickle.load(open("scaler_5feature.pkl", 'rb'))

In [37]:
preinput_data = [[2, 1, 2, 1, 1]]

In [38]:
preinput_scaled = loaded_scaler.transform(preinput_data)
result = loaded_model.predict(preinput_scaled)

C:\Users\Admin\anaconda3\envs\aids\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"

In [39]:
print(f"Prediction: {result}")
if result[0] == 1:
    print("Lung Cancer Prediction Result: Positive")
else:
    print("Lung Cancer Prediction Result: Negative")

Prediction: [1]
Lung Cancer Prediction Result: Positive